/* Toda a microcopy da tela, nas duas línguas. EN-US é a referência: chave sem
   tradução cai no inglês. Chave organizada por componente. */

export const DICIONARIO = {
  en: {
    'paginas.tudo': 'everything',
    'paginas.fase': 'phase',
    'paginas.adiadas': 'deferred',
    /* comum */
    'comum.fechar': 'Close',
    'comum.cancelar': 'Cancel',
    'comum.guardar': 'Save',
    'comum.acrescentar': 'Add',
    'comum.remover': 'Remove',
    'comum.copiar': 'Copy',
    'comum.copiado': 'Copied',
    'comum.entenda': 'Learn more',

    /* cabeçalho */
    'cab.org.placeholder': 'organization',
    'cab.org.rotulo': 'Project organization',
    'cab.org.desc': 'Goes in front of the project name and in every generated path.',
    'cab.projeto.placeholder': 'Project name',
    'cab.salvar': 'Save .bio',
    'cab.salvar.rotulo': 'Save the project',
    'cab.salvar.desc': 'Writes a .bio file (drawing, settings and accounts) in the working folder.',
    'cab.config': 'Settings',
    'cab.config.rotulo': 'Project settings',
    'cab.config.desc': 'Naming, regions, domains and AWS accounts. New elements are born with these values.',
    'cab.ajuda': 'Help',
    'cab.ajuda.rotulo': 'Help and glossary',
    'cab.ajuda.desc': 'FAQ, short articles and every bioma term explained.',
    'cab.limpar': 'Clear canvas',
    'cab.limpar.rotulo': 'Clear the canvas',
    'cab.limpar.desc': 'Asks first and offers a zip of what exists.',

    /* barra de comando */
    'barra.verCodigo': 'View code',
    'barra.verCodigo.rotulo': 'Open the generated code',
    'barra.verCodigo.desc': 'Folder tree and every generated file, in a drawer over the canvas.',
    'barra.pendencias': 'Questions',
    'diag.camada.1': 'layer 1 · the element',
    'diag.camada.2': 'layer 2 · the drawing',
    'diag.camada.3': 'layer 3 · the connection',
    'diag.camada.4': 'layer 4 · the output',
    'barra.pendencias.rotulo': 'Open the questions',
    'barra.pendencias.desc': 'Each field waiting for an answer, with the accepted format and a valid example. Answer right there.',
    'barra.pendencias.aria': 'Questions: {n} waiting for an answer',
    'barra.etiqueta': 'The command that will run',
    'barra.vazio': 'Add an element and the full command appears here',
    'barra.rodando': 'Running',
    'barra.conferindo': 'Checking…',
    'barra.rodandoAgora': 'Running…',
    'barra.simular': 'Simulate',
    'barra.simular.bandeira': 'no changes',
    'barra.simular.rotulo': 'Simulate without applying',
    'barra.simular.desc': 'Runs the checks, then {cmd}. Nothing is created or destroyed.',
    'barra.aplicar': 'Apply',
    'barra.aplicar.rotulo': 'Apply to the cloud',
    'barra.aplicar.desc': 'The checks run before {cmd}. A blocked check opens the questions and the command does not run.',
    'barra.destruir': 'Destroy',
    'barra.destruir.travado': 'Destroy waits for a declared change window',
    'barra.motivo.checagens': 'checks',
    'barra.motivo.consequencia': 'the command will not run while this check is blocked',
    'barra.motivo.arvore': 'tree',
    'barra.motivo.semArvore': 'without a tree to check, nothing is simulated or applied',
    'barra.motivo.conferencia': 'check',
    'barra.motivo.bloqueada': 'one of the checks is blocked',
    'barra.motivo.bloqueioDePe': 'the command will not run while the block stands',
    'barra.motivo.servidor': 'the server did not answer: {erro}',

    /* canvas */
    'canvas.tecido.permanente': 'permanent',
    'canvas.tecido.estavel': 'stable',
    'canvas.tecido.efemera': 'ephemeral',
    'canvas.tecido.termo': 'fabric',
    'canvas.caixa.conta': 'Account',
    'canvas.caixa.dominio': 'Domain',
    'canvas.caixa.arrastar': 'Drag to move the whole account',
    'canvas.conta.escolha': 'Choose the account',
    'canvas.conta.artefato': 'no account: handed to the pipeline',
    'canvas.conta.fora': 'not registered',
    'canvas.conta.nenhuma': 'No account registered',
    'canvas.conta.aria': 'The account where {nome} lives',
    'canvas.pino.entrada': 'Connect another element into {nome}',
    'canvas.pino.saida': 'Connect {nome} into another element',
    'canvas.semLeitura': 'not classified',
    'canvas.lendo': 'reading…',
    'canvas.aviso.fixado': 'Click the target element to connect, or empty space to cancel',
    'canvas.legenda.titulo': 'The bioma classifies the arrow',
    'canvas.legenda.esconder': 'Hide legend',
    'canvas.legenda.mostrar': 'Show arrow legend',
    'canvas.legenda.lead': 'You connect two elements. The bioma reads both ends and picks the drawing.',
    'canvas.legenda.dep': 'same account on both ends becomes a',
    'canvas.legenda.dep.termo': 'dependency',
    'canvas.legenda.lig': 'different accounts become a',
    'canvas.legenda.lig.termo': 'cross-account connection',
    'canvas.legenda.cifra': 'a security element on one end becomes',
    'canvas.legenda.cifra.termo': 'key or secret',
    'canvas.legenda.dica': 'Drag from a pin to another element to connect',
    'canvas.telaCheia': 'Full screen',
    'canvas.telaCheia.sair': 'Exit full screen',
    'canvas.afastar': 'Zoom out',
    'canvas.aproximar': 'Zoom in',
    'canvas.enquadrar': 'Fit the whole drawing',

    /* página inicial */
    'inicio.tagline': 'Architecture drawing in, Terraform and Terragrunt structure out.',
    'inicio.importar': 'Open a drawing',
    'inicio.importar.desc': 'Block spec (.md), poster (.html/.png) or a saved .bio project',
    'inicio.zero': 'Start from zero',
    'inicio.zero.desc': 'Search an AWS resource and build on the canvas',
    'inicio.exemplo': 'Open the example',
    'inicio.exemplo.desc': 'A working drawing with accounts and settings filled in',
    'inicio.recentes': 'Recent projects',
    'inicio.atalho': 'cmd+K to search',

    /* ferramenta da peça e exclusão */
    'peca.papel.rotulo': 'What it does here',
    'peca.papel.placeholder': 'e.g., audit trail of events',
    'peca.papel.dica': 'Feeds the generated name and the file layout',
    'peca.excluir': 'Delete element',
    'excluir.titulo': 'Delete {nome}?',
    'excluir.corpo': 'The element and its arrows leave the drawing and the generated files. There is no undo.',
    'excluir.confirmar': 'Delete',

    /* estado e avisos da composição */
    'tela.estado.traduzindo': 'translating the drawing…',
    'tela.estado.parou': 'translation stopped',
    'tela.estado.resumo': '{arquivos} files · {pecas} elements',
    'tela.estado.vazio': 'no element on the canvas',
    'tela.veu': 'Reading the drawing… an image goes through a vision model and takes 10 to 60 seconds. Elements appear when it finishes.',
    'tela.solte': 'Drop the drawing here',
    'tela.levar': 'Take to my machine',
    'tela.levar.rotulo': 'Download the zip or write the tree to a folder',
    'tela.referencia.subido': 'Uploaded drawing',
    'tela.erro.parou': 'Translation stopped',
    'tela.servidor': 'the server did not answer: {erro}',

    /* modais */
    'limpeza.titulo': 'Clear the whole drawing?',
    'limpeza.corpo': '{pecas} element(s) and {setas} arrow(s) will be removed. There is no undo. To keep a copy, download the zip first.',
    'limpeza.ficar': 'Keep as is',
    'limpeza.baixar': 'Download first',
    'limpeza.apagar': 'Clear everything',
    'destruir.titulo': 'Declare the change window',
    'destruir.corpo': 'You are stating the window was agreed with whoever operates. Write when it is, and the ticket if one exists. The text goes into the command and stays in the run log.',
    'destruir.agora': 'Now',
    'destruir.hoje': 'Today 22:00',
    'destruir.amanha': 'Tomorrow 22:00',
    'destruir.imediata': 'immediate window',
    'destruir.placeholder': '2026-08-06 22:00 to 23:30, ticket CHG-1042',
    'destruir.hint': 'Click a shortcut above or write it as YEAR-MONTH-DAY HOUR:MINUTE',
    'destruir.nota': 'What goes down: ephemeral fabric always, stable fabric because you declared the window. Permanent fabric does not go down this way, and the checks list which is which before running.',
    'destruir.ficar': 'Keep as is',
    'destruir.confirmar': 'Check and destroy',
    'destruir.janela.aria': 'Change window',
    'levar.titulo': 'Take the tree to your machine',
    'levar.corpo': 'The zip carries the whole tree. Writing to a folder puts the same files in an empty path on your machine.',
    'levar.placeholder': '~/my-project/infra',
    'levar.pasta.aria': 'Target folder',
    'levar.fechar': 'Close',
    'levar.zip': 'Download .zip',
    'levar.gravar': 'Write to folder',
    'levar.montando': 'building the zip…',
    'levar.pronto': 'bioma.zip is in your downloads folder',
    'levar.gravando': 'writing…',
    'levar.gravado': '{quantos} files in {destino}',

    /* trilho direito (inspetor) */
    'trilho.titulo': 'Inspector',
    'trilho.abrir': 'Open the inspector',
    'trilho.fechar': 'Close the inspector',
    'trilho.aba.peca': 'Element',
    'trilho.aba.decisoes': 'Decisions',
    'trilho.aba.ligacoes': 'Connections',
    'trilho.abertura': 'Every element you drew needs a folder, a file and a rule for what happens if it goes down. The bioma worked that out and lists it here, with the reason. Change it now if you disagree: after it is applied, changing means migrating.',
    'trilho.nada': 'Put an element on the canvas. Everything the bioma works out about it shows up here, with the reason.',
    'trilho.unidade': 'unit',
    'trilho.unidades': 'units',
    'trilho.porResponder': '{n} waiting for an answer',
    'trilho.porque': 'Why the bioma decided this',
    'trilho.responder': 'Answer',
    'trilho.espera': 'waits for an answer',
    'trilho.aceito': 'Accepted value',
    'trilho.exemplo': 'Example',
    'trilho.confirmar': 'Worth checking',
    'trilho.abrirFicha': 'Open this element to edit it',
    'trilho.rotulo.tipo': 'what it is',
    'trilho.rotulo.tecido': 'if it goes down',
    'trilho.rotulo.onde': 'where it lives',
    'trilho.ligacoes.vazio': 'No arrow connected yet. Connect one element to another and the translator classifies the crossing.',
    'trilho.etiqueta.permanente': 'permanent fabric',
    'trilho.etiqueta.estavel': 'stable cell',
    'trilho.etiqueta.efemera': 'ephemeral',
    'trilho.etiqueta.ligacao': 'connection',
    'trilho.etiqueta.artefato': 'artifact, handed to the pipeline',
    'trilho.etiqueta.desconhecida': 'unknown nature',
    'trilho.peca.vazia': 'Click an element on the canvas. Its form appears here, one question per value the recipe requires.',

    /* ficha da célula (campos base) */
    'ficha.nome.pergunta': 'What this cell will be called',
    'ficha.nome.explica': 'lowercase letters, numbers, dot, hyphen or underscore; 3 to 63 characters',
    'ficha.nome.erra': 'a name outside the pattern stops the process before touching the cloud; a repeated name in the same account conflicts at apply',
    'ficha.conta.pergunta': 'Which AWS account it lives in',
    'ficha.conta.explica': 'exactly 12 digits, no hyphen',
    'ficha.conta.erra': 'the wrong account grants access to the wrong people, and the resource is born outside its domain',
    'ficha.regiao.pergunta': 'Which region it is born in',
    'ficha.regiao.explica': 'country-area-number, like sa-east-1 (São Paulo)',
    'ficha.regiao.erra': 'the wrong region creates the resource far from where the data must live; moving later is a migration',

    /* painel da célula */
    'celula.rotulo': 'The cell',
    'celula.escolhaRegiao': 'Choose the region',
    'celula.doi': 'What breaks if this is wrong',
    'celula.doi.aria': 'What breaks if {campo} is wrong',
    'celula.aceita': 'accepts {formato}',
    'celula.outroFormato': 'another format',
    'celula.exemploDica': 'example: {exemplo}',
    'celula.semNome': 'unnamed cell',
    'celula.fronteira': 'boundary',
    'celula.tecidoPorDecidir': 'fabric undecided',
    'celula.tecido.rotulo': 'The fabric, which decides what can go down',
    'celula.foraNossa': 'Not ours',
    'celula.foraNossa.texto': 'the zone declares SaaS: the service stays out of what the tool creates and destroys.',
    'celula.durabilidade': 'Durability',
    'celula.decidiu': 'the bioma decided {v}',
    'celula.naoDecidiu.titulo': 'the translator has not decided yet',
    'celula.naoDecidiu.texto': 'no option comes marked until the proposal arrives. Choose now or wait for the reading to finish.',
    'celula.trocou': 'You switched to {v}. The destroy order now follows your choice.',
    'celula.receita': 'What the recipe requires',
    'celula.receita.vazia': 'This recipe asks for no value beyond the ones above. When the generator writes the form, the questions appear here.',
    'celula.aceitos': '{a} of {t} accepted',
    'celula.foraFormato': 'Wrong format',
    'celula.semResposta': 'No answer',
    'celula.passa': 'The form passes the fill check',
    'tela.contaDoTradutor': 'The translator put this cell in {conta}. Write its 12-digit number.',

    /* gaveta do código */
    'gc.rotulo': 'Code',
    'gc.aba.arquivos': 'Files',
    'gc.aba.saida': 'Run output',
    'gc.aviso': 'Generated files are not edited by hand. The drawing and the form are the source; the next generation overwrites.',
    'gc.espera.um': '1 file waiting for an answer',
    'gc.espera.varios': '{n} files waiting for an answer',
    'gc.responder': 'Waiting for an answer · Answer it',
    'gc.responder.title': 'Opens the question that fills this file',
    'gc.escolha': 'Pick a file on the left. It shows whole, uncut.',
    'gc.linhas': '{n} lines',
    'gc.vazia.titulo': 'The tree is born with the first element',
    'gc.vazia.corpo': 'Each element on the canvas becomes folders and files here, immediately.',
    'gc.nada': 'Nothing in this tab yet',
    'gc.fechar': 'Close the code drawer',
    'gc.borda': 'Drag to change the drawer height',
    'gc.esc': 'closes',
    'gc.pendente.title': 'waiting for an answer',
    'gc.saida.vazia': 'No run yet. Simulate or apply and the command output lands here.',

    /* gaveta de pendências */
    'gp.titulo': 'Questions',
    'gp.celulaSemNome': 'unnamed cell',
    'gp.campoSemNome': 'unnamed field',
    'gp.abrirNaPeca': 'Open in element',
    'gp.aplicar': 'Apply',
    'gp.aceita': 'What is accepted',
    'gp.exemplo': 'Valid example',
    'gp.seFicar': 'If it stays like this',
    'gp.resumo.um': '1 field waits for an answer',
    'gp.resumo.varios': '{n} fields wait for an answer',
    'gp.resumo.celulas': 'in {c} cell(s)',
    'gp.efeito': 'Simulate and apply run the checks first and stop here while any of these fields is empty or off-format. Answer right here, or open the element.',
    'gp.vazio.titulo': 'No field waiting for an answer',
    'gp.vazio.corpo': 'Every required field in the drawing is filled. Simulate and apply will not stop here.',
    'gp.voltar': 'Back to the drawing',
    'gp.placeholder': 'Type the answer',
    'gp.foraFormato': 'Not in the accepted format yet',
    'gp.respondido': 'Answered',

    /* configurações */
    'cfg.titulo': 'Settings',
    'cfg.aba.projeto': '1 · Project',
    'cfg.aba.dominios': '2 · Domains',
    'cfg.aba.contas': '3 · Accounts',
    'cfg.callout.titulo': 'Values that apply to the whole project',
    'cfg.callout.corpo': 'A new element is born with the acronym, the default region and the account of its domain. Elements created before adjust via Apply.',
    'cfg.sigla': 'Project acronym',
    'cfg.sigla.hint': 'Starts the name of every element',
    'cfg.padraoNome': 'Name pattern',
    'cfg.padraoNome.hint': 'Available pieces: {sigla}, {recurso}, {funcao}',
    'cfg.ficaAssim': 'Looks like:',
    'cfg.pasta': 'Working folder',
    'cfg.pasta.hint': 'Where the drawing is saved and where the command runs',
    'cfg.pasta.nenhuma': 'No folder chosen',
    'cfg.escolher': 'Choose',
    'cfg.fecharNav': 'Close',
    'cfg.usarEsta': 'Use this one',
    'cfg.subir': '.. up one level',
    'cfg.semSub': 'No subfolder here',
    'cfg.regioes': 'Project regions',
    'cfg.regiao.busca': 'Search the region: são paulo, virginia, ireland…',
    'cfg.regiao.nenhuma': 'No region chosen',
    'cfg.regiao.semTexto': 'No region matches this text',
    'cfg.regiao.nota': 'Click a chosen region to make it the default.',
    'cfg.padrao': 'default',
    'cfg.dom.callout.titulo': 'Domain',
    'cfg.dom.callout.corpo': 'Becomes an account and a folder in the generated structure. A child domain nests under its parent folder. An arrow between domains becomes a cross-account connection.',
    'cfg.dominios': 'Project domains',
    'cfg.dom.filho': 'Add child',
    'cfg.dom.novo': 'Add domain',
    'cfg.dom.placeholder': 'Payments',
    'cfg.dom.filhoDe': 'Child of {pai}',
    'cfg.dom.tirar': 'Remove {nome}',
    'cfg.dom.contas': '{n} account(s)',
    'cfg.dom.nenhum': 'No domain yet: pick a starter set below',
    'cfg.conjunto': 'Or start from a set',
    'cfg.preset.simples': 'Simple',
    'cfg.preset.simples.desc': 'Application, data and security. For a start and for small products.',
    'cfg.preset.plataforma': 'Platform',
    'cfg.preset.plataforma.desc': 'Four domains, separating network from security.',
    'cfg.preset.referencia': 'Reference architecture',
    'cfg.preset.referencia.desc': 'Six domains, with the delivery pipeline and what is external. Not every project needs this size.',
    'cfg.contas.callout.titulo': 'AWS accounts',
    'cfg.contas.callout.corpo': 'Each account belongs to a domain. A new element is born in the default account of its domain.',
    'cfg.conta.apelido': 'Alias',
    'cfg.conta.numero': 'Number',
    'cfg.conta.dominio': 'Domain',
    'cfg.conta.dominio.escolha': 'Domain…',
    'cfg.conta.cadastrar': 'Add account',
    'cfg.conta.tornarPadrao': 'Make default',
    'cfg.conta.semDominio': 'no domain',
    'cfg.conta.nenhuma': 'No account registered',
    'cfg.conta.tirar': 'Remove account {nome}',
    'cfg.conta.erroNumero': 'The account number has exactly 12 digits, no hyphen',
    'cfg.conta.erroApelido': 'Give the account an alias',
    'cfg.guardar': 'Save',
    'cfg.aplicar': 'Apply to existing elements',
    'cfg.guardando': 'saving…',
    'cfg.guardado': 'saved',
    'cfg.naoDeu': 'Could not save',

    /* gaveta de ajuda */
    'ga.titulo': 'Help',
    'ga.aba.faq': 'FAQ',
    'ga.aba.glossario': 'Glossary',
    'ga.abertura.faq': 'Questions by topic. Each answer ends in the action that solves it.',
    'ga.abertura.glossario': 'The vocabulary the screen uses, and what each word decides at generation time.',
    'ga.exemplo': 'Example',
    'ga.saibaMais': 'Learn more',

    /* paleta */
    'pk.aria': 'Search AWS resources',
    'pk.placeholder': 's3, queue, vpc, lambda…',
    'pk.maisUsados': 'Most used',
    'pk.procurando': 'Searching',
    'pk.cortado': 'First {n} · type more to narrow down',
    'pk.encontrados': '{n} found',
    'pk.exige': '{n} required argument(s)',
    'pk.outros': 'others',
    'pk.fora': 'The server did not answer; resource search depends on it',
    'pk.buscando': 'Searching the provider schema',
    'pk.nenhum': 'No AWS resource matches "{termo}"',
    'pk.anda': 'moves through the list',
    'pk.poe': 'puts it on the canvas',
    'pk.fecha': 'closes',

    /* trilho esquerdo */
    'pr.titulo': 'Elements',
    'pr.vazio': 'Nothing on the canvas yet. Open the search and pick the first AWS resource.',
    'pr.buscar': 'Search resource',
    'pr.abrir': 'Open the elements rail',
    'pr.fechar': 'Collapse the elements rail',
    'tela.semArvore': 'the tree has not been generated yet',
    'tela.travado': 'The drawing has not generated a tree yet',

    /* assistente de projeto */
    'wz.titulo': 'Set up the project',
    'wz.passo': 'Step {n} of {t}',
    'wz.p1.titulo': 'Project',
    'wz.p1.desc': 'These values name every element and every generated path.',
    'wz.org': 'Organization',
    'wz.org.hint': 'Goes in front of the project name and in every generated path',
    'wz.nome': 'Project name',
    'wz.regiao': 'Default region',
    'wz.p2.titulo': 'Domains',
    'wz.p2.desc': 'Domains become accounts and folders. Pick a starter set; adjust anytime in Settings › Domains.',
    'wz.p3.titulo': 'Accounts',
    'wz.p3.desc': 'Register the AWS accounts your elements will live in. The first one becomes the default. You can add more later.',
    'wz.contas.vazia': 'No account yet.',
    'wz.voltar': 'Back',
    'wz.avancar': 'Next',
    'wz.concluir': 'Finish',
    'wz.depois': 'Configure later',
    'pk.todos': 'All services',
    'pk.recursosDo': '{n} resources',
    'celula.oQueFalta': '{n} to answer',

    'canvas.seta.remover': 'Remove this connection',
    'canvas.seta.titulo': 'Remove the connection?',
    'canvas.seta.corpo': 'The arrow between {de} and {para} leaves the drawing, and the files it generated go with it.',
    'celula.conta.escolha': 'Choose the account',
    'celula.conta.cadastrar': 'No account registered. Add one in Settings › Accounts.',

    'cfg.dom.travado': 'In use: {onde}. Move what uses it first.',
    'cfg.dom.usoConta': '{n} account(s)',
    'cfg.dom.usoPeca': '{n} element(s) on the canvas',
    'cfg.dom.confirmar.titulo': 'Remove {nome}?',
    'cfg.dom.confirmar.filhos': 'It has {n} nested domain(s), which go with it: {lista}.',
    'cfg.dom.confirmar.corpo': 'The domain leaves the project. Nothing on the canvas changes now, but new elements can no longer be born in it.',
    'canvas.vazio.titulo': 'Empty canvas',
    'canvas.vazio.corpo': 'The project is open. Search an AWS resource to put the first element back.',

    'pasta.titulo': 'Choose the working folder',
    'pasta.corpo': 'The .bio project, the generated tree and the command all live in this folder.',
    'pasta.usar': 'Use this folder',
    'visao.usouMd': 'Read from the spec next to the image ({nome}).',
    'visao.forcar': 'Read the image instead',
    'visao.lendo': 'Reading the image with the vision model…',

    'rev.botao': 'Review',
    'rev.rotulo': 'Have it reviewed',
    'rev.desc': 'Runs the checks, compiles each recipe with terraform, and asks a senior AWS reviewer what works and what does not.',
    'rev.titulo': 'Review',
    'rev.rodando': 'Reviewing… compiling the recipes and reading the tree. Takes a couple of minutes.',
    'rev.vazio': 'No review yet. Press Review and the verdict lands here.',
    'rev.ok': 'works',
    'rev.falha': 'does not work',
    'rev.risco': 'costs later',
    'rev.conserto': 'To fix',
    'rev.onde': 'Where',
    'rev.fonte.verificador': 'bioma check',
    'rev.refazer': 'Review again',

    'receita.rotulo': 'The recipe',
    'receita.criar': 'Create and update',
    'receita.destruir': 'Destroy',
    'receita.desc': 'The bioma writes the commands; your team runs them, in your pipeline, with your credentials. What must not go down is already locked in the generated code.',
    'receita.copiar': 'Copy the recipe',
    'receita.trava': 'Refuses to destroy: {n} permanent cell(s)',
    'receita.travaNenhuma': 'No permanent cell in this drawing',
    'receita.janela': 'Change window, for the record',
    /* fim-en */
  },
  pt: {
    'paginas.tudo': 'tudo',
    'paginas.fase': 'fase',
    'paginas.adiadas': 'adiadas',
    /* comum */
    'comum.fechar': 'Fechar',
    'comum.cancelar': 'Cancelar',
    'comum.guardar': 'Salvar',
    'comum.acrescentar': 'Acrescentar',
    'comum.remover': 'Remover',
    'comum.copiar': 'Copiar',
    'comum.copiado': 'Copiado',
    'comum.entenda': 'Saiba mais',

    /* cabeçalho */
    'cab.org.placeholder': 'organizacao',
    'cab.org.rotulo': 'Organização do projeto',
    'cab.org.desc': 'Entra na frente do nome do projeto e em todo caminho gerado.',
    'cab.projeto.placeholder': 'Nome do projeto',
    'cab.salvar': 'Salvar .bio',
    'cab.salvar.rotulo': 'Salvar o projeto',
    'cab.salvar.desc': 'Grava um arquivo .bio (desenho, configuração e contas) na pasta de trabalho.',
    'cab.config': 'Configurações',
    'cab.config.rotulo': 'Configurações do projeto',
    'cab.config.desc': 'Nomes, regiões, domínios e contas AWS. Elemento novo nasce com estes valores.',
    'cab.ajuda': 'Ajuda',
    'cab.ajuda.rotulo': 'Ajuda e glossário',
    'cab.ajuda.desc': 'FAQ, artigos curtos e cada termo do bioma explicado.',
    'cab.limpar': 'Limpar canvas',
    'cab.limpar.rotulo': 'Limpar o canvas',
    'cab.limpar.desc': 'Pergunta antes e oferece o zip do que existe.',

    /* barra de comando */
    'barra.verCodigo': 'Ver código',
    'barra.verCodigo.rotulo': 'Abrir o código gerado',
    'barra.verCodigo.desc': 'Árvore de pastas e cada arquivo gerado, em gaveta por cima do canvas.',
    'barra.pendencias': 'Pendências',
    'diag.camada.1': 'camada 1 · a peça',
    'diag.camada.2': 'camada 2 · o desenho',
    'diag.camada.3': 'camada 3 · a ligação',
    'diag.camada.4': 'camada 4 · a saída',
    'barra.pendencias.rotulo': 'Abrir as pendências',
    'barra.pendencias.desc': 'Cada campo que espera resposta, com o formato aceito e um exemplo válido. Responda ali mesmo.',
    'barra.pendencias.aria': 'Pendências: {n} esperando resposta',
    'barra.etiqueta': 'O comando que vai rodar',
    'barra.vazio': 'Acrescente um elemento e o comando aparece aqui, inteiro',
    'barra.rodando': 'Rodando',
    'barra.conferindo': 'Conferindo…',
    'barra.rodandoAgora': 'Rodando…',
    'barra.simular': 'Simular',
    'barra.simular.bandeira': 'sem aplicar',
    'barra.simular.rotulo': 'Simular sem aplicar',
    'barra.simular.desc': 'Roda as verificações e depois {cmd}. Nada é criado nem destruído.',
    'barra.aplicar': 'Aplicar',
    'barra.aplicar.rotulo': 'Aplicar na nuvem',
    'barra.aplicar.desc': 'As verificações rodam antes de {cmd}. Checagem bloqueada abre as pendências e o comando não sai.',
    'barra.destruir': 'Destruir',
    'barra.destruir.travado': 'A destruição espera a janela de mudança declarada',
    'barra.motivo.checagens': 'verificações',
    'barra.motivo.consequencia': 'o comando não roda enquanto esta checagem estiver bloqueada',
    'barra.motivo.arvore': 'árvore',
    'barra.motivo.semArvore': 'sem árvore para conferir, nada é simulado nem aplicado',
    'barra.motivo.conferencia': 'conferência',
    'barra.motivo.bloqueada': 'uma das verificações está bloqueada',
    'barra.motivo.bloqueioDePe': 'o comando não roda enquanto o bloqueio estiver de pé',
    'barra.motivo.servidor': 'o servidor não respondeu: {erro}',

    /* canvas */
    'canvas.tecido.permanente': 'permanente',
    'canvas.tecido.estavel': 'estável',
    'canvas.tecido.efemera': 'efêmera',
    'canvas.tecido.termo': 'tecido',
    'canvas.caixa.conta': 'Conta',
    'canvas.caixa.dominio': 'Domínio',
    'canvas.caixa.arrastar': 'Arraste para mover a conta inteira',
    'canvas.conta.escolha': 'Escolha a conta',
    'canvas.conta.artefato': 'sem conta: entregue à esteira',
    'canvas.conta.fora': 'fora do cadastro',
    'canvas.conta.nenhuma': 'Nenhuma conta cadastrada',
    'canvas.conta.aria': 'A conta onde {nome} mora',
    'canvas.pino.entrada': 'Ligar outra peça em {nome}',
    'canvas.pino.saida': 'Ligar {nome} em outra peça',
    'canvas.semLeitura': 'sem leitura',
    'canvas.lendo': 'lendo…',
    'canvas.aviso.fixado': 'Clique na peça de destino para ligar, ou no vazio para desistir',
    'canvas.legenda.titulo': 'Quem classifica a seta é o bioma',
    'canvas.legenda.esconder': 'Esconder legenda',
    'canvas.legenda.mostrar': 'Mostrar a legenda das setas',
    'canvas.legenda.lead': 'Você liga duas peças. O bioma lê as duas pontas e escolhe o desenho.',
    'canvas.legenda.dep': 'mesma conta nas duas pontas vira',
    'canvas.legenda.dep.termo': 'dependência',
    'canvas.legenda.lig': 'contas diferentes viram',
    'canvas.legenda.lig.termo': 'ligação entre contas',
    'canvas.legenda.cifra': 'peça de segurança numa ponta vira',
    'canvas.legenda.cifra.termo': 'chave ou segredo',
    'canvas.legenda.dica': 'Arraste de um pino até a outra peça para ligar',
    'canvas.telaCheia': 'Tela cheia',
    'canvas.telaCheia.sair': 'Sair da tela cheia',
    'canvas.afastar': 'Afastar',
    'canvas.aproximar': 'Aproximar',
    'canvas.enquadrar': 'Enquadrar o desenho inteiro',

    /* página inicial */
    'inicio.tagline': 'Desenho de arquitetura entra, estrutura Terraform e Terragrunt sai.',
    'inicio.importar': 'Abrir um desenho',
    'inicio.importar.desc': 'Especificação do bloco (.md), poster (.html/.png) ou um projeto .bio salvo',
    'inicio.zero': 'Começar do zero',
    'inicio.zero.desc': 'Busque um recurso AWS e monte no canvas',
    'inicio.exemplo': 'Abrir o exemplo',
    'inicio.exemplo.desc': 'Um desenho funcionando, com contas e configuração preenchidas',
    'inicio.recentes': 'Projetos recentes',
    'inicio.atalho': 'cmd+K para buscar',

    /* ferramenta da peça e exclusão */
    'peca.papel.rotulo': 'O que ela faz aqui',
    'peca.papel.placeholder': 'ex.: trilha de auditoria dos eventos',
    'peca.papel.dica': 'Alimenta o nome gerado e o desenho dos arquivos',
    'peca.excluir': 'Excluir peça',
    'excluir.titulo': 'Excluir {nome}?',
    'excluir.corpo': 'A peça e as setas dela saem do desenho e dos arquivos gerados. Não existe desfazer.',
    'excluir.confirmar': 'Excluir',

    /* estado e avisos da composição */
    'tela.estado.traduzindo': 'traduzindo o desenho…',
    'tela.estado.parou': 'a tradução parou',
    'tela.estado.resumo': '{arquivos} arquivos · {pecas} peças',
    'tela.estado.vazio': 'nenhuma peça no canvas',
    'tela.veu': 'Lendo o desenho… imagem passa por um modelo de visão e leva de 10 a 60 segundos. As peças entram no quadro quando terminar.',
    'tela.solte': 'Solte o desenho aqui',
    'tela.levar': 'Levar para a máquina',
    'tela.levar.rotulo': 'Baixar o zip ou gravar a árvore numa pasta',
    'tela.referencia.subido': 'Desenho subido',
    'tela.erro.parou': 'A tradução parou',
    'tela.servidor': 'o servidor não respondeu: {erro}',

    /* modais */
    'limpeza.titulo': 'Apagar o desenho inteiro?',
    'limpeza.corpo': '{pecas} peça(s) e {setas} seta(s) somem, e não existe desfazer. Para guardar uma cópia, baixe o zip antes.',
    'limpeza.ficar': 'Ficar como está',
    'limpeza.baixar': 'Baixar antes',
    'limpeza.apagar': 'Apagar tudo',
    'destruir.titulo': 'Declare a janela de mudança',
    'destruir.corpo': 'Você está afirmando que a janela foi combinada com quem opera. Escreva quando é, e o chamado quando existir. O texto vai inteiro para o comando e fica no diário da execução.',
    'destruir.agora': 'Agora',
    'destruir.hoje': 'Hoje 22:00',
    'destruir.amanha': 'Amanhã 22:00',
    'destruir.imediata': 'janela imediata',
    'destruir.placeholder': '2026-08-06 22:00 a 23:30, chamado MUD-1042',
    'destruir.hint': 'Clique num atalho acima ou escreva no formato ANO-MÊS-DIA HORA:MINUTO',
    'destruir.nota': 'O que cai: tecido efêmero sempre, e estável porque você declarou a janela. Tecido permanente não cai por este caminho, e as verificações mostram quais são antes de rodar.',
    'destruir.ficar': 'Ficar como está',
    'destruir.confirmar': 'Conferir e destruir',
    'destruir.janela.aria': 'Janela de mudança',
    'levar.titulo': 'Levar a árvore para a sua máquina',
    'levar.corpo': 'O zip traz a árvore inteira. Gravar na pasta escreve os mesmos arquivos num caminho vazio da sua máquina.',
    'levar.placeholder': '~/meu-projeto/infra',
    'levar.pasta.aria': 'Pasta de destino',
    'levar.fechar': 'Fechar',
    'levar.zip': 'Baixar .zip',
    'levar.gravar': 'Gravar na pasta',
    'levar.montando': 'montando o zip…',
    'levar.pronto': 'bioma.zip na sua pasta de downloads',
    'levar.gravando': 'gravando…',
    'levar.gravado': '{quantos} arquivos em {destino}',

    /* trilho direito (inspetor) */
    'trilho.titulo': 'Inspetor',
    'trilho.abrir': 'Abrir o inspetor',
    'trilho.fechar': 'Fechar o inspetor',
    'trilho.aba.peca': 'Peça',
    'trilho.aba.decisoes': 'Decisões',
    'trilho.aba.ligacoes': 'Ligações',
    'trilho.abertura': 'Toda peça que você desenhou precisa de uma pasta, de um arquivo e de uma regra do que acontece se ela cair. O bioma resolveu isso e lista aqui, com o motivo. Discorde agora se for o caso: depois de aplicado, mudar vira migração.',
    'trilho.nada': 'Ponha uma peça no canvas. Tudo que o bioma resolver sobre ela aparece aqui, com o motivo.',
    'trilho.unidade': 'unidade',
    'trilho.unidades': 'unidades',
    'trilho.porResponder': '{n} esperando resposta',
    'trilho.porque': 'Por que o bioma decidiu assim',
    'trilho.responder': 'Responder',
    'trilho.espera': 'espera resposta',
    'trilho.aceito': 'Valor aceito',
    'trilho.exemplo': 'Exemplo',
    'trilho.confirmar': 'Vale conferir',
    'trilho.abrirFicha': 'Abrir esta peça para editar',
    'trilho.rotulo.tipo': 'o que é',
    'trilho.rotulo.tecido': 'se cair',
    'trilho.rotulo.onde': 'onde mora',
    'trilho.ligacoes.vazio': 'Nenhuma seta ligada até agora. Ligue uma peça na outra e o tradutor classifica a travessia.',
    'trilho.etiqueta.permanente': 'tecido permanente',
    'trilho.etiqueta.estavel': 'célula estável',
    'trilho.etiqueta.efemera': 'efêmera',
    'trilho.etiqueta.ligacao': 'ligação',
    'trilho.etiqueta.artefato': 'artefato, entregue à esteira',
    'trilho.etiqueta.desconhecida': 'natureza desconhecida',
    'trilho.peca.vazia': 'Clique numa peça do canvas. A ficha dela aparece aqui, uma pergunta por valor que a receita exige.',

    /* ficha da célula (campos base) */
    'ficha.nome.pergunta': 'Como esta célula vai se chamar',
    'ficha.nome.explica': 'minúsculas, números, ponto, hífen ou sublinhado; de 3 a 63 caracteres',
    'ficha.nome.erra': 'nome fora do padrão para o processo antes de tocar a nuvem; nome repetido na mesma conta conflita no apply',
    'ficha.conta.pergunta': 'Em que conta AWS ela mora',
    'ficha.conta.explica': 'exatamente 12 dígitos, sem hífen',
    'ficha.conta.erra': 'conta errada dá permissão a quem não devia, e o recurso nasce fora do domínio dono dele',
    'ficha.regiao.pergunta': 'Em que região ela nasce',
    'ficha.regiao.explica': 'no formato pais-area-numero, como sa-east-1 (São Paulo)',
    'ficha.regiao.erra': 'região errada cria o recurso longe de onde o dado precisa morar; mover depois é migração',

    /* painel da célula */
    'celula.rotulo': 'A célula',
    'celula.escolhaRegiao': 'Escolha a região',
    'celula.doi': 'O que quebra se isto estiver errado',
    'celula.doi.aria': 'O que quebra se {campo} estiver errado',
    'celula.aceita': 'aceita {formato}',
    'celula.outroFormato': 'outro formato',
    'celula.exemploDica': 'exemplo: {exemplo}',
    'celula.semNome': 'célula sem nome',
    'celula.fronteira': 'fronteira',
    'celula.tecidoPorDecidir': 'tecido por decidir',
    'celula.tecido.rotulo': 'O tecido, que decide o que pode cair',
    'celula.foraNossa': 'Não é nossa',
    'celula.foraNossa.texto': 'a zona declara SaaS: o serviço fica de fora do que a ferramenta cria e destrói.',
    'celula.durabilidade': 'Durabilidade',
    'celula.decidiu': 'o bioma decidiu {v}',
    'celula.naoDecidiu.titulo': 'o tradutor ainda não decidiu',
    'celula.naoDecidiu.texto': 'nenhuma opção vem marcada até a proposta chegar. Escolha agora ou espere a leitura terminar.',
    'celula.trocou': 'Você trocou para {v}. A ordem de destruição passa a seguir a sua escolha.',
    'celula.receita': 'O que a receita exige',
    'celula.receita.vazia': 'Esta receita não pede nenhum valor além dos de cima. Quando o gerador escrever a ficha, as perguntas aparecem aqui.',
    'celula.aceitos': '{a} de {t} aceitos',
    'celula.foraFormato': 'Fora do formato',
    'celula.semResposta': 'Sem resposta',
    'celula.passa': 'A ficha passa no verificador de preenchimento',
    'tela.contaDoTradutor': 'O tradutor pôs esta célula na {conta}. Escreva o número de 12 dígitos dela.',

    /* gaveta do código */
    'gc.rotulo': 'Código',
    'gc.aba.arquivos': 'Arquivos',
    'gc.aba.saida': 'Saída da execução',
    'gc.aviso': 'Arquivo gerado não se edita à mão. O desenho e a ficha são a fonte; a próxima geração sobrescreve.',
    'gc.espera.um': '1 arquivo espera resposta',
    'gc.espera.varios': '{n} arquivos esperam resposta',
    'gc.responder': 'Espera resposta · Responder',
    'gc.responder.title': 'Abre a pergunta que preenche este arquivo',
    'gc.escolha': 'Escolha um arquivo à esquerda. Ele aparece inteiro, sem corte.',
    'gc.linhas': '{n} linhas',
    'gc.vazia.titulo': 'A árvore nasce com a primeira peça',
    'gc.vazia.corpo': 'Cada peça no canvas vira pasta e arquivo aqui, na hora.',
    'gc.nada': 'Nada nesta aba ainda',
    'gc.fechar': 'Fechar a gaveta do código',
    'gc.borda': 'Arrastar para mudar a altura da gaveta',
    'gc.esc': 'fecha',
    'gc.pendente.title': 'espera resposta',
    'gc.saida.vazia': 'Nenhuma execução ainda. Simule ou aplique e a saída do comando aparece aqui.',

    /* gaveta de pendências */
    'gp.titulo': 'Pendências',
    'gp.celulaSemNome': 'célula sem nome',
    'gp.campoSemNome': 'campo sem nome',
    'gp.abrirNaPeca': 'Abrir na peça',
    'gp.aplicar': 'Aplicar',
    'gp.aceita': 'O que se aceita',
    'gp.exemplo': 'Exemplo válido',
    'gp.seFicar': 'Se ficar como está',
    'gp.resumo.um': '1 campo espera resposta',
    'gp.resumo.varios': '{n} campos esperam resposta',
    'gp.resumo.celulas': 'em {c} célula(s)',
    'gp.efeito': 'Simular e aplicar rodam as verificações antes e param aqui enquanto qualquer destes campos estiver vazio ou fora do formato. Responda aqui mesmo, ou abra a peça.',
    'gp.vazio.titulo': 'Nenhum campo esperando resposta',
    'gp.vazio.corpo': 'Todo campo obrigatório do desenho está preenchido. Simular e aplicar seguem sem parar aqui.',
    'gp.voltar': 'Voltar ao desenho',
    'gp.placeholder': 'Escreva a resposta',
    'gp.foraFormato': 'Ainda fora do formato aceito',
    'gp.respondido': 'Respondido',

    /* configurações */
    'cfg.titulo': 'Configurações',
    'cfg.aba.projeto': '1 · Projeto',
    'cfg.aba.dominios': '2 · Domínios',
    'cfg.aba.contas': '3 · Contas',
    'cfg.callout.titulo': 'Valores que valem para o projeto inteiro',
    'cfg.callout.corpo': 'Peça nova nasce com a sigla, a região padrão e a conta do domínio dela. Peça criada antes se ajusta pelo Aplicar.',
    'cfg.sigla': 'Sigla do projeto',
    'cfg.sigla.hint': 'Entra no começo do nome de toda peça',
    'cfg.padraoNome': 'Padrão do nome',
    'cfg.padraoNome.hint': 'Peças disponíveis: {sigla}, {recurso}, {funcao}',
    'cfg.ficaAssim': 'Fica assim:',
    'cfg.pasta': 'Pasta de trabalho',
    'cfg.pasta.hint': 'Onde o desenho é gravado e onde o comando roda',
    'cfg.pasta.nenhuma': 'Nenhuma pasta escolhida',
    'cfg.escolher': 'Escolher',
    'cfg.fecharNav': 'Fechar',
    'cfg.usarEsta': 'Usar esta',
    'cfg.subir': '.. subir um nível',
    'cfg.semSub': 'Nenhuma subpasta aqui',
    'cfg.regioes': 'Regiões do projeto',
    'cfg.regiao.busca': 'Procure a região: são paulo, virgínia, irlanda…',
    'cfg.regiao.nenhuma': 'Nenhuma região escolhida',
    'cfg.regiao.semTexto': 'Nenhuma região com esse texto',
    'cfg.regiao.nota': 'Clique numa região escolhida para torná-la a padrão.',
    'cfg.padrao': 'padrão',
    'cfg.dom.callout.titulo': 'Domínio',
    'cfg.dom.callout.corpo': 'Vira conta e pasta na estrutura gerada. Domínio filho aninha sob a pasta do pai. Seta entre domínios vira ligação entre contas.',
    'cfg.dominios': 'Domínios do projeto',
    'cfg.dom.filho': 'Criar filho',
    'cfg.dom.novo': 'Criar domínio',
    'cfg.dom.placeholder': 'Pagamentos',
    'cfg.dom.filhoDe': 'Filho de {pai}',
    'cfg.dom.tirar': 'Remover {nome}',
    'cfg.dom.contas': '{n} conta(s)',
    'cfg.dom.nenhum': 'Nenhum domínio ainda: escolha um conjunto abaixo',
    'cfg.conjunto': 'Ou comece por um conjunto',
    'cfg.preset.simples': 'Simples',
    'cfg.preset.simples.desc': 'Aplicação, dados e segurança. Para começar e para produto pequeno.',
    'cfg.preset.plataforma': 'Plataforma',
    'cfg.preset.plataforma.desc': 'Quatro domínios, separando rede de segurança.',
    'cfg.preset.referencia': 'Arquitetura de referência',
    'cfg.preset.referencia.desc': 'Seis domínios, com esteira e o que é de fora. Nem todo projeto precisa desse tamanho.',
    'cfg.contas.callout.titulo': 'Contas AWS',
    'cfg.contas.callout.corpo': 'Cada conta pertence a um domínio. Peça nova nasce na conta padrão do domínio dela.',
    'cfg.conta.apelido': 'Apelido',
    'cfg.conta.numero': 'Número',
    'cfg.conta.dominio': 'Domínio',
    'cfg.conta.dominio.escolha': 'Domínio…',
    'cfg.conta.cadastrar': 'Cadastrar conta',
    'cfg.conta.tornarPadrao': 'Tornar padrão',
    'cfg.conta.semDominio': 'sem domínio',
    'cfg.conta.nenhuma': 'Nenhuma conta cadastrada',
    'cfg.conta.tirar': 'Remover a conta {nome}',
    'cfg.conta.erroNumero': 'O número da conta tem exatamente 12 dígitos, sem hífen',
    'cfg.conta.erroApelido': 'Dê um apelido à conta',
    'cfg.guardar': 'Salvar',
    'cfg.aplicar': 'Aplicar no que já existe',
    'cfg.guardando': 'salvando…',
    'cfg.guardado': 'salvo',
    'cfg.naoDeu': 'Não deu para salvar',

    /* gaveta de ajuda */
    'ga.titulo': 'Ajuda',
    'ga.aba.faq': 'FAQ',
    'ga.aba.glossario': 'Glossário',
    'ga.abertura.faq': 'Perguntas por assunto. Cada resposta termina na ação que resolve.',
    'ga.abertura.glossario': 'O vocabulário que a tela usa, com o que cada palavra decide na hora de gerar.',
    'ga.exemplo': 'Exemplo',
    'ga.saibaMais': 'Saiba mais',

    /* paleta */
    'pk.aria': 'Buscar recurso da AWS',
    'pk.placeholder': 's3, fila, vpc, lambda…',
    'pk.maisUsados': 'Mais usados',
    'pk.procurando': 'Procurando',
    'pk.cortado': 'Primeiros {n} · escreva mais para estreitar',
    'pk.encontrados': '{n} encontrados',
    'pk.exige': '{n} argumento(s) obrigatório(s)',
    'pk.outros': 'outros',
    'pk.fora': 'O servidor não respondeu; a busca de recurso depende dele',
    'pk.buscando': 'Procurando no esquema do provider',
    'pk.nenhum': 'Nenhum recurso da AWS com "{termo}"',
    'pk.anda': 'anda na lista',
    'pk.poe': 'põe no canvas',
    'pk.fecha': 'fecha',

    /* trilho esquerdo */
    'pr.titulo': 'Elementos',
    'pr.vazio': 'Nada no canvas ainda. Abra a busca e escolha o primeiro recurso da AWS.',
    'pr.buscar': 'Buscar recurso',
    'pr.abrir': 'Abrir o trilho de elementos',
    'pr.fechar': 'Recolher o trilho de elementos',
    'tela.semArvore': 'a árvore ainda não foi gerada',
    'tela.travado': 'O desenho ainda não gerou árvore',

    /* assistente de projeto */
    'wz.titulo': 'Configurar o projeto',
    'wz.passo': 'Passo {n} de {t}',
    'wz.p1.titulo': 'Projeto',
    'wz.p1.desc': 'Estes valores nomeiam toda peça e todo caminho gerado.',
    'wz.org': 'Organização',
    'wz.org.hint': 'Entra na frente do nome do projeto e em todo caminho gerado',
    'wz.nome': 'Nome do projeto',
    'wz.regiao': 'Região padrão',
    'wz.p2.titulo': 'Domínios',
    'wz.p2.desc': 'Domínio vira conta e pasta. Escolha um conjunto de partida; ajuste quando quiser em Configurações › Domínios.',
    'wz.p3.titulo': 'Contas',
    'wz.p3.desc': 'Cadastre as contas AWS onde as peças vão morar. A primeira vira a padrão. Dá para acrescentar mais depois.',
    'wz.contas.vazia': 'Nenhuma conta ainda.',
    'wz.voltar': 'Voltar',
    'wz.avancar': 'Avançar',
    'wz.concluir': 'Concluir',
    'wz.depois': 'Configurar depois',
    'pk.todos': 'Todos os serviços',
    'pk.recursosDo': '{n} recursos',
    'celula.oQueFalta': '{n} por responder',

    'canvas.seta.remover': 'Remover esta ligação',
    'canvas.seta.titulo': 'Remover a ligação?',
    'canvas.seta.corpo': 'A seta entre {de} e {para} sai do desenho, e os arquivos que ela gerou saem junto.',
    'celula.conta.escolha': 'Escolha a conta',
    'celula.conta.cadastrar': 'Nenhuma conta cadastrada. Cadastre em Configurações › Contas.',

    'cfg.dom.travado': 'Em uso: {onde}. Mova quem usa antes.',
    'cfg.dom.usoConta': '{n} conta(s)',
    'cfg.dom.usoPeca': '{n} peça(s) no canvas',
    'cfg.dom.confirmar.titulo': 'Remover {nome}?',
    'cfg.dom.confirmar.filhos': 'Ele tem {n} domínio(s) aninhado(s), que saem junto: {lista}.',
    'cfg.dom.confirmar.corpo': 'O domínio sai do projeto. Nada muda no canvas agora, mas peça nova não nasce mais nele.',
    'canvas.vazio.titulo': 'Canvas vazio',
    'canvas.vazio.corpo': 'O projeto continua aberto. Busque um recurso da AWS para pôr a primeira peça de volta.',

    'pasta.titulo': 'Escolha a pasta de trabalho',
    'pasta.corpo': 'O projeto .bio, a árvore gerada e o comando moram nesta pasta.',
    'pasta.usar': 'Usar esta pasta',
    'visao.usouMd': 'Li a especificação ao lado da imagem ({nome}).',
    'visao.forcar': 'Ler a imagem em vez disso',
    'visao.lendo': 'Lendo a imagem com o modelo de visão…',

    'rev.botao': 'Revisar',
    'rev.rotulo': 'Mandar revisar',
    'rev.desc': 'Roda as verificações, compila cada receita com o terraform e pergunta a um revisor AWS sênior o que funciona e o que não.',
    'rev.titulo': 'Revisão',
    'rev.rodando': 'Revisando… compilando as receitas e lendo a árvore. Leva alguns minutos.',
    'rev.vazio': 'Nenhuma revisão ainda. Aperte Revisar e o parecer aparece aqui.',
    'rev.ok': 'funciona',
    'rev.falha': 'não funciona',
    'rev.risco': 'cobra depois',
    'rev.conserto': 'Para consertar',
    'rev.onde': 'Onde',
    'rev.fonte.verificador': 'verificação do bioma',
    'rev.refazer': 'Revisar de novo',

    'receita.rotulo': 'A receita',
    'receita.criar': 'Criar e atualizar',
    'receita.destruir': 'Destruir',
    'receita.desc': 'O bioma escreve os comandos; quem roda é o seu time, no pipeline de vocês, com a credencial de vocês. O que não pode cair já está travado no código gerado.',
    'receita.copiar': 'Copiar a receita',
    'receita.trava': 'Recusa destruir: {n} célula(s) permanente(s)',
    'receita.travaNenhuma': 'Nenhuma célula permanente neste desenho',
    'receita.janela': 'Janela de mudança, para o registro',
    /* fim-pt */
  },
}
